### ISSUE TITLE
Crash upon button press

### ISSUE THREAD

**Issue by skymike** [Danimal4326/homebridge-hyperion#12]
Crash log:

http://pasted.co/a70a648e

**Comment by Danimal4326** [comment]
this was fixed.  either downgrade your version of color or reinstall homebridge-hyperion

**Comment by skymike** [comment]
I did both, still crashing.
could this be related to using RBG color setting?
